version: '3.8'
services:
  db:
    image: postgres:17
    container_name: footballSquare_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: footballSquare
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data  # 데이터 저장 볼륨

volumes:
  db_data:

