version: '3.8'

services:
  db:
    image: postgres:17
    container_name: footballSquare_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: footballSquare
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: footballSquare_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: footballsquare-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./src/.env

  chat-server:
    build:
      context: ./chat
      dockerfile: Dockerfile.prod  
    container_name: footballsquare-chat
    ports:
      - "3001:3001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - ./chat/.env

volumes:
  db_data:
  redis_data:
