const { TEAM_ROLE } = require("./team")
const { MATCH_PARTICIPATION_TYPE, MATCH_ATTRIBUTE, MATCH_TYPE, MATCH_FORMATION,MATCH_DURATION } = require('./match');
const { COMMUNITY_ROLE,COMMUNINY_IDX } = require('./community');
const { COMMON_STATUS } = require("./common")
const { CHAMPIONSHIP_TYPE, CHAMPIONSHIP_STATUS } = require("./championship")

module.exports = {
    TEAM_ROLE,
    MATCH_PARTICIPATION_TYPE,
    MATCH_ATTRIBUTE,
    MATCH_TYPE,
    MATCH_FORMATION,
    MATCH_DURATION,
    COMMUNITY_ROLE,
    COMMUNINY_IDX,
    COMMON_STATUS,
    CHAMPIONSHIP_TYPE,
    CHAMPIONSHIP_STATUS
};